### ISSUE TITLE
Features request 

### ISSUE THREAD

**Issue by allmightyasian** [zadeviggers/wallpaper#4]
Please add multi touch support,
Also something like fluid simulation will be better,
And a option for disappearing shapes like time setting

**Comment by zadeviggers** [comment]
Thanks for the suggestions!

- Multi-touch is a good idea - I'll probably add that soon.
- Adding fluid simulation is a non-goal. Other wallpapers have that.
- What sort of timescale would you want for the shapes disappearing: seconds, minutes, or hours? All three?

**Comment by zadeviggers** [comment]
Version 15.8 is out with multi-touch support

**Comment by allmightyasian** [comment]
> Thanks for the suggestions!
> 
> * Multi-touch is a good idea - I'll probably add that soon.
> * Adding fluid simulation is a non-goal. Other wallpapers have that.
> * What sort of timescale would you want for the shapes disappearing: seconds, minutes, or hours? All three?

Seconds, if you can't add fluid simulation, so please add something else, like a snake just like Nokia's old game, other shapes will be good,

**Comment by zadeviggers** [comment]
I'm not adding snake.
I did add a star shape type (https://github.com/zadeviggers/wallpaper/commit/b031ebe2c64bee37ecff2c0ac3c19604b3995485). If you want new shape types, feel free to suggest them in a new issue.
